= M-JC1-66-20

The material for the group M-JC1-66-20

== Lessons

|===
|№|Theme|Date|Due date|Homework|Test
|1|Введение|22.12.2020|24.12.2020|link:https://github.com/rakovets/course-java-basics/tree/intro[branch: intro]|link:https://forms.gle/XHwuj6ZJbbUqP7xA6[intro]
|2|Типы данных. Переменные. Операторы|24.12.2020|30.12.2020|link:https://github.com/rakovets/course-java-basics/tree/operators[branch: operators]|-
|===

== Process

image::./images/process.svg[Process]

Процесс работы над темами, которые изучаются на занятиях:

* прочитать теоритический материал (контроль: test, влият на GRADE)
* выполнить задания предложенные преподавателем (контроль: manual review with your unit-tests, влияет на GRADE)
** одно задание - один commit
** сделать push на GitHub
** сделать Pull Request в соответствующую ветку root repository
** на выполнение задания отводится 6 дней, следующих за днем когда занятие по этой теме состоялось
* выполнить задания в рабочей тетради (контроль: manual review with trainer, не влияет на GRADE)

== Communication

* *Telegram*:
** Зарегистрироваться.
** Отправить сообщение тренеру, которое содержит Ваше имя и фамилию на английском языке, используя никнейм `@rakovets` или номер `+375297902100`.
*** В случае возникновения проблем с поиском, напишите тренеру на email
** Временно отключаем настройки политики по добавлению в группу, так как тренер не сможет добавить в группу
** После этого, Вы будете добавлены в 2 группы:
*** `M-JC1-66-20-dev` - используется для взаимодействия в группе
*** `M-JC1-66-20-prod` - используется для объявлений и решения вопросов/проблем, которые не могли быть решены в первой, так как преподаватель мог не увидеть/прочитать Ваше сообщение.

* *Gmail*:
** Зарегистрироваться.
** Подписываемся на *YouTube* канал: link:https://www.youtube.com/channel/UCIztUGTxSCyqksE3HxFgI_w[Dmitry Rakovets].
** Отправить сообщение тренеру в Telegram, которое содержит Ваш *email* (*gmail*).
** После этого вы получите доступ к *электронному журналу*, который сожержит текущие отметки.
** На этот *email*, так же будет предоставляться доступ к закрытым видео на *YuoTube*, если таковые будут.

* *GitHub*:
** Зарегистрироваться.
** Подписываемя на пользователя: link:https://www.github.com/rakovets[Dmitry Rakovets].
** Ставим "звездочку" для репозитория `course-java-basics`, `wiki`, `presentation`.
** Делаем `fork` для репозитория `course-java-basics`.
** Почти все задания будут выполняться в репозитории `course-java-basics`.

* *LinkedIn*:
** Зарегистрироваться.
** Отправляем `Connect` пользователю: link:https://www.linkedin.com/in/rakovets/[Dmitry Rakovets].
** Оформляем текущее место работы: IT-academy, Trainee (можно подсмотреть у преподавателя).

== Software

* link:https://jdk.java.net/java-se-ri/11[OpenJDK 11]
* link:https://www.jetbrains.com/idea/download[IntelliJ IDEA Community Edition]
* link:https://git-scm.com/[Git]
